### ISSUE TITLE
Simplificação do parse do text_table

### ISSUE THREAD

**Issue by eduardoklosowski** [jsbueno/advent_of_code_2023#1]
As [linhas 47 e 48](https://github.com/jsbueno/advent_of_code_2023/blob/4240d462dfab04e77c37dbe702c4a5ec34bc9e5c/dia5.py#L47-L48) do construtor da classe `Table` poderia ser simplificadas:

```python
# De
header, body = text_table.split("\n", 1)
lines = body.split("\n")

# Para
header, *lines = text_table.split("\n")
```

**Comment by jsbueno** [comment]
Boa! Nem.lembrava mesmo da star expansion usada assim

Se isso aqui respeitasse o esprrito original do gitnoa dar pra por um patch aqui e eu aplicar daqui mesmo. (E não você ter que criar um fork do projeto inteiro, etc...)

**Comment by eduardoklosowski** [comment]
É um pouco trabalhoso, mas PR aberto.
